//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InfWizard.rc
//
#define VERSION_MINOR                   0
#define VERSION_MICRO                   0
#define IDS_INFWIZARD                   1
#define VERSION_NANO                    1
#define IDS_HEADERTITLE                 2
#define VERSION_MAJOR                   2
#define IDS_HEADERSUBTITLE              3
#define IDS_PAGE_SELECT_DEVICE_TITLE    4
#define IDS_PAGE_SELECT_DEVICE_SUBTITLE 5
#define IDS_VENDOR_ID                   6
#define IDS_PRODUCT_ID                  7
#define IDS_DESCRIPTION                 8
#define IDS_INSTALLED_DRIVER            9
#define IDS_DLL_USB0_NOT_SUPPORTED      10
#define IDS_DLL_USB0_SUPPORTED          11
#define IDS_DLL_USB1_NOT_SUPPORTED      12
#define IDS_DLL_USB1_SUPPORTED          13
#define IDS_DLL_USBK_SUPPORTED          14
#define IDS_PAGE_CONFIG_DEVICE_TITLE    15
#define IDS_PAGE_CONFIG_DEVICE_SUBTITLE 16
#define IDS_MI                          17
#define IDS_GUID                        18
#define IDS_DEVICE_ID                   19
#define IDS_HARDWARE_ID                 20
#define IDS_PAGE_INSTALL_TITLE          21
#define IDS_PAGE_INSTALL_SUBTITLE       22
#define IDS_MANUFACTURER                23
#define IDS_TIP_SAVE_BASE_FOLDER        24
#define IDS_TIP_PACKAGE_NAME            25
#define IDS_TXT_CLIENT_INSTALLER        26
#define IDS_TXT_LEGACY_PACKAGE          27
#define IDS_TXT_INSTALL_ONLY            28
#define IDS_STATUS_START_PACKAGER       29
#define IDS_STATUS_INVALID_PATH         30
#define IDS_STATUS_PREPARE_DRIVER       31
#define IDS_ERROR_PREPARE_DRIVER        32
#define IDS_STATUS_INSTALL_DRIVER       33
#define IDS_ERROR_INSTALL_DRIVER        34
#define IDS_STATUS_PACKAGE_SUCCESS      35
#define IDS_PACKAGE_DIR                 36
#define IDS_PACKAGE_NAME                37
#define IDS_TIP_OPEN_SESSION            38
#define IDS_TIP_SAVE_SESSION            39
#define IDS_TIP_SHOW_NEW_DEVICES        40
#define IDS_TIP_SHOW_ALL_DEVICES        41
#define IDS_TIP_VENDOR_ID               42
#define IDS_TIP_PRODUCT_ID              43
#define IDS_TIP_MANUFACTURER            44
#define IDS_TIP_DEVICE_DESCRIPTION      45
#define IDS_TIP_INTERFACE_NUMBER        46
#define IDS_TIP_INTERFACE_GUID          47
#define IDS_TIP_CLIENT_INSTALLER        48
#define IDS_TIP_LEGACY_PACKAGE          49
#define IDS_TIP_INSTALL_ONLY            50
#define IDS_TIP_EXPLORE_PACKAGE_FOLDER  51
#define IDS_TIP_EXPLORE_BASE_FOLDER     52
#define IDS_INF_CLASS                   53
#define IDS_INF_CLASS_GUID              54
#define IDS_INF_PROVIDER                55
#define IDS_TIP_INF_CLASS               56
#define IDS_TIP_INF_CLASS_GUID          57
#define IDS_TIP_INF_PROVIDER            58
#define IDS_NEXT                        59
#define IDS_BACK                        60
#define IDS_CANCEL                      61
#define IDS_FINISH                      62
#define IDSF_PATH_TO_LONG               63
#define IDS_CREATE_FILE_FAILED          64
#define IDSF_CREATE_FILE_FAILED         64
#define IDS_STATUS_CREATE_USER_INSTALLER 65
#define IDS_STATUS_EXPORT_INSTALLER_RESOURCES 66
#define IDSE_CREATE_USER_INSTALLER      67
#define IDSE_UNKNOWN                    68
#define IDSE_STATUS_PACKAGE             69
#define IDS_PAGE_POWER_MANAGEMENT_TITLE 70
#define IDS_PAGE_POWER_MANAGEMENT_SUBTITLE 71
#define IDS_TIP_DEVICE_IDLE_ENABLED     72
#define IDS_TIP_DEFAULT_IDLE_STATE      73
#define IDS_TIP_DEFAULT_IDLE_TIMEOUT    74
#define IDS_TIP_USER_SET_DEVICE_IDLE_ENABLED 75
#define IDS_TIP_DEVICE_IDLE_IGNORE_WAKE_ENABLE 76
#define IDS_TIP_SYSTEM_WAKE_ENABLED     77
#define IDS_ABOUTBOX                    101
#define IDC_BIGBOLDTITLE                102
#define IDC_BOLDTITLE                   103
#define IDC_LBL_FINISHED_CAPTION        104
#define IDC_LBL_FINISHED_TEXT           105
#define IDC_TRANSPARENT3                106
#define IDC_DRIVER_LIST                 107
#define IDC_DEV_LIST                    109
#define IDC_BTN_SAVE_BASE_FOLDER        110
#define IDC_BTN_OPEN_PACKAGE_FOLDER     110
#define IDC_SUPPORTED_DRIVERS_TEXT2     111
#define IDD_PAGE_INTRO                  112
#define IDD_PAGE_SELECT_DEVICE          113
#define IDD_PAGE_CONFIG_DEVICE          114
#define IDD_PAGE_INSTALL                115
#define IDD_PAGE_FINISHED               116
#define IDR_MAINFRAME                   200
#define IDB_BANNER                      201
#define IDB_WATERMARK                   202
#define IDC_INTRO_TEXT1                 203
#define IDC_INTRO_TEXT2                 204
#define IDC_EDIT1                       1000
#define IDC_TXT_SAVE_BASE_FOLDER        1000
#define IDS_PAGE_INTRO_TITLE            1001
#define IDC_TXT_SAVE_BASE_FOLDER2       1001
#define IDC_TXT_SAVE_NAME               1001
#define IDC_GROUP1                      1002
#define IDC_STATIC_TITLE                1003
#define IDC_LBL_DEFAULT_IDLE_TIMEOUT            1003
#define IDI_BMPOK                       2001
#define IDI_ICON_OK                     2001
#define IDI_BMPSTOP                     2002
#define IDI_ICON_STOP                   2002
#define IDI_ICON_BREAK                  2003
#define IDB_BAR_BLUE                    2025
#define IDB_BAR_GREEN                   2026
#define IDB_BAR_ORANGE                  2027
#define IDI_ICON_EXCLAMATION            2030
#define IDI_ICON_OPEN_FOLDER            2031
#define IDI_ICON_INFO                   2032
#define IDI_ICON_INFORMATION            2032
#define IDI_ICON_NAV_BACK               2044
#define IDI_ICON_NAV_NEXT               2045
#define IDI_ICON_NAV_CANCEL             2046
#define IDI_ICON_NAV_FINISH             2047
#define IDD_DIALOG1                     2048
#define IDD_DIALOG_PROGRESS             2048
#define IDD_PAGE_POWER_MANAGEMENT       2049
#define IDI_ICON_DONATE                 2051
#define IDC_SHOW_NEW_DEVICES            3002
#define IDC_SHOW_ALL_DEVICES            3003
#define IDC_BTN_LEGACY_PACKAGE          3003
#define IDC_BTN_CLIENT_INSTALLER        3004
#define IDC_BTN_INSTALL_ONLY            3005
#define IDC_GRP_SAVE_INFORMATION        3006
#define IDC_TXT_STATUS                  3007
#define IDC_GRP_STATUS                  3008
#define IDC_LBL_SAVE_BASE_FOLDER        3009
#define IDC_LBL_SAVE_NAME               3010
#define IDC_LINK_OPEN_SESSION           3010
#define IDC_LBL_TEXT_FINISH             3010
#define IDC_LINK_SAVE_SESSION           3011
#define IDC_LINK_EXPLORE_PACKAGE_FOLDER 3012
#define IDC_LINK_EXPLORE_BASE_FOLDER    3013
#define IDC_LINK_INSTALL_DRIVER_NOW     3013
#define IDC_PIC_FINISHED_TEXT           3014
#define IDC_GRP_ADDITIONAL_TASKS        3016
#define IDC_BTN_EXPLORE_PACKAGE_FOLDER  3017
#define IDC_BTN_EXPLORE_BASE_FOLDER     3018
#define IDC_LBL_EXPLORE_PACKAGE_FOLDER  3019
#define IDC_LBL_EXPLORE_BASE_FOLDER     3020
#define IDC_LINK_SELECT_DRIVER          3021
#define IDC_LBL_TEXT_BACK               3022
#define IDC_PIC_TEXT_BACK               3024
#define ID_PIC_PROGRESS                 3028
#define IDC_CTL_PROGRESS                3029
#define IDC_TXT_PROGRESS                3030
#define IDC_SYSLINK_POWER_MANAGEMENT    3031
#define IDC_CHK_DEVICE_IDLE_ENABLED     3033
#define IDC_GRP_POWER                   3034
#define IDC_CHK_DEFAULT_IDLE_STATE      3035
#define IDC_CBO_DEFAULT_IDLE_TIMEOUT    3036
#define IDC_CHK_USER_SET_DEVICE_IDLE_ENABLED 3037
#define IDC_CHK_DEVICE_IDLE_IGNORE_WAKE_ENABLE 3038
#define IDC_CHK_SYSTEM_WAKE_ENABLED     3039

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2052
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         3037
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
