@ECHO OFF
SETLOCAL ENABLEEXTENSIONS ENABLEDELAYEDEXPANSION
SET _ZIP_DIR=%~dp0\USB_Device_Benchmark\Firmware\output\
SET _ZIP_NAME=%~1.7z
IF EXIST "!_ZIP_NAME!" DEL /Q "!_ZIP_NAME!"
7z a "!_ZIP_NAME!" "!_ZIP_DIR!*"
