/* "doscmd.dll" version header. ++ auto-generated
*/
#ifndef VERSION

#define _DEFINE_TO_STR(x) #x
#define  DEFINE_TO_STR(x) _DEFINE_TO_STR(x)

#define VERSION_MAJOR 1
#define VERSION_MINOR 2
#define VERSION_MICRO 2
#define VERSION_NANO 19
#define VERSION_DATE 07/20/2021
#define RC_FILENAME_STR "doscmd.dll"

#define RC_VERSION VERSION_MAJOR,VERSION_MINOR,VERSION_MICRO,VERSION_NANO
#define VERSION VERSION_MAJOR.VERSION_MINOR.VERSION_MICRO.VERSION_NANO
#define RC_VERSION_STR DEFINE_TO_STR(VERSION)
#define VERSION_DATE_STR DEFINE_TO_STR(VERSION_DATE)

#endif
